---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

```


`r emo::ji("warning")` Wir haben die Entwicklung des Dashboards und des [R Packages](https://github.com/friep/vaccc19de) eingestellt. `r emo::ji("warning")`

**Wieso gibt es das Dashboard nicht mehr?**

Dieses Projekt war eine relativ spontane Kollaboration zwischen uns ([Fabio](https://github.com/favstats) und [Frie](https://github.com/friep)), nachdem wir unabhängig voneinander festgestellt hatten, dass 

1) vom RKI keine Zeitreihendaten veröffentlicht wurden, sondern täglich die Daten überschrieben wurden (-> Datenverlust für die Öffentlichkeit)
2) es kein Dashboard / Visualisierung von öffentlicher Seite gab 

Inzwischen gibt es jedoch für beide Probleme bessere Lösungen als unsere: 

Bzgl. 1) gibt es das [RKI-Impf-Archiv](https://github.com/ard-data/2020-rki-impf-archive), welches wir in den letzten Wochen auch für unser Dashboard verwendet haben. 

Bzgl. 2) Auch wenn im [offiziellen Dashboard](https://impfdashboard.de/) einige wichtige Analysen fehlen (z.B. gibt es keine Aufschlüsselung auf Bundesländer-Ebene) (e.g. no Bundesland-level analyses), ist es jedoch eine gute, offizielle Informationsquelle. 

Schlussendlich können wir - angesichts des sich andauernd wandelnden Datenformats der Exceldatei, welche ständige Anpassungen am Code erfordert - realistischerweise die Integrität und Korrektheit der Visualisierungen nicht garantieren, zumal wir dieses Projekt in unserer Freizeit gestartet und verfolgt hatten. 



