---
output: html_document
---



```{r setup, include=FALSE}
library(flexdashboard)
# library(vaccc19de)
library(tidyverse)
library(highcharter)

knitr::opts_chunk$set(echo = F, message = F, warning = F)


source("../R/utils.R")

frie_dat <- read_csv("https://raw.githubusercontent.com/friep/vaccc19de_rki_data/main/data/cumulative_time_series.csv")

rki_dat <- dir("../data/", full.names = T) %>% 
  keep(~str_detect(.x, "csv")) %>% 
  purrr::map_dfr(read_csv) %>% 
  bind_rows(frie_dat) %>% 
  distinct(ts_datenstand, bundesland, .keep_all = T) %>% 
  mutate(day = lubridate::as_date(ts_datenstand)) 

pop_dat <- readRDS("../data/pop_dat.RDS")

rki_dat <- rki_dat %>% 
  left_join(pop_dat) %>% 
  mutate(prozent_geimpft = impfungen_kumulativ/insgesamt*100)

saveRDS(rki_dat, file = "../data/rki_dat.RDS")


latest_dat <- rki_dat %>% 
  dplyr::filter(day==max(day))
```





### Karten

```{r, out.width="100%"}
    
prozent_plot <- hcmap(
  "https://code.highcharts.com/mapdata/countries/de/de-all.js",
  data = latest_dat,
  value = "prozent_geimpft",
  joinBy = c("name", "bundesland"),
  name = "% der Bevölkerung geimpft",
    dataLabels = list(enabled = TRUE, format = "{point.name}"),
    tooltip = list(
      valueDecimals = 2,
      valueSuffix = "%"
    )
  ) %>%
  hc_exporting(
    enabled = TRUE
)  %>% 
  hc_credits(
    enabled = TRUE, text = "Quelle: Robert Koch-Institut.",
    href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
    style = list(fontSize = "12px")
  ) %>%
  hc_title(
    text = "Prozent der Bevölkerung geimpft"
  ) %>% 
  hc_legend(
    layout = "horizontal",
    verticalAlign = "top",
    align = "center",
    valueDecimals = 0
  )%>%
  hc_colorAxis(
    stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Blues 3", rev = T))
  )

total_plot <- hcmap(
  "https://code.highcharts.com/mapdata/countries/de/de-all.js",
  data = latest_dat,
  value = "impfungen_kumulativ",
  joinBy = c("name", "bundesland"),
  name = "Anzahl der Impfungen",
  dataLabels = list(enabled = TRUE, format = "{point.name}")
  ) %>%
  hc_exporting(
    enabled = TRUE
  )  %>% 
  hc_credits(
    enabled = TRUE, text = "Quelle: Robert Koch-Institut",
    href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
    style = list(fontSize = "12px")
  ) %>%
  hc_title(
    text = " Anzahl der Impfungen"
  ) %>% 
  hc_legend(
    layout = "horizontal",
    verticalAlign = "top",
    align = "center",
    valueDecimals = 0
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Mint", rev = T))
  )




hw_grid(prozent_plot, total_plot, ncol = 2)

```



Row
-----------------------------------------------------------------------

### Anzahl der der Impfungen {.value-box}

```{r}


geimpft <- latest_dat %>% 
  summarize(impfungen_kumulativ = sum(impfungen_kumulativ)) %>% pull(impfungen_kumulativ)

  valueBox(
    value = geimpft,
    icon = "fa-users",
    color = "info"
  )
```


### Prozent der Bevölkerung geimpft {.value-box}

```{r}


pop <- latest_dat %>% 
  summarize(insgesamt = sum(insgesamt)) %>% pull(insgesamt)



  valueBox(
    value = paste0(round(geimpft/pop*100, 2), "%"),
    icon = "fa-syringe",
    color = "success"
  )
```

