---
title: "Impfungen nach Bundesland"
output: 
  html_document:
    theme: yeti
---




```{r setup, include=FALSE}
# library(vaccc19de)
library(tidyverse)
library(highcharter)

knitr::opts_chunk$set(echo = F, message = F, warning = F)

source("../../R/utils.R")

rki_dat <- readRDS("../../data/rki_dat.RDS")

de_dat <- rki_dat %>% 
  filter(bundesland == "Deutschland")  %>% 
  select(day, de_impfungen_kumulativ_label = impfungen_kumulativ_label,
         de_prozent_geimpft_label = prozent_geimpft_label)

rki_dat <- rki_dat %>% 
  filter(bundesland != "Deutschland")

latest_dat <- rki_dat %>% 
  dplyr::filter(day==max(day))

prelatest_dat <- rki_dat %>% 
  dplyr::filter(day<max(day)) %>% 
  dplyr::filter(day==max(day))


latest_dat <- latest_dat %>% 
  mutate(impfungen_lasttime = prelatest_dat$impfungen_kumulativ,
         impfungen_lasttime = impfungen_kumulativ-impfungen_lasttime,
         prozent_lasttime = (impfungen_lasttime)/impfungen_kumulativ*100) %>% 
  mutate(prozent_lasttime_label = round(prozent_lasttime, 2)) %>% 
  mutate(impfungen_lasttime_label = scales::label_number()(impfungen_lasttime) %>% str_remove_all("\\.0"))
```


<br>

```{r, out.width="100%"}
    
prozent_plot <- hcmap(
  "https://code.highcharts.com/mapdata/countries/de/de-all.js",
  data = latest_dat,
  value = "prozent_geimpft",
  joinBy = c("name", "bundesland"),
  name = "Impfdosen pro 100 Einwohner",
    dataLabels = list(enabled = TRUE, format = "{point.name}"),
    tooltip = list(
      valueDecimals = 2
    )
  ) %>%
  hc_exporting(
    enabled = TRUE
)  %>% 
  hc_credits(
    enabled = TRUE, text = "Quelle: Robert Koch-Institut.",
    href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
    style = list(fontSize = "12px")
  ) %>%
  hc_title(
    text = "Impfdosen pro 100 Einwohner",
    verticalAlign = "top",
    align = "center"
  ) %>% 
  hc_legend(
    layout = "horizontal",
    verticalAlign = "top",
    align = "center",
    valueDecimals = 0
  )%>%
  hc_colorAxis(
    stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Blues 3", rev = T))
  ) %>%
  highcharter::hc_add_theme(highcharter::hc_theme_smpl())

total_plot <- hcmap(
  "https://code.highcharts.com/mapdata/countries/de/de-all.js",
  data = latest_dat,
  value = "impfungen_kumulativ",
  joinBy = c("name", "bundesland"),
  name = "Anzahl der Impfungen",
  dataLabels = list(enabled = TRUE, format = "{point.name}")
  ) %>%
  hc_exporting(
    enabled = TRUE
  )  %>% 
  hc_credits(
    enabled = TRUE, text = "Quelle: Robert Koch-Institut",
    href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
    style = list(fontSize = "12px")
  ) %>%
  hc_title(
    text = "Anzahl der Impfungen",
    verticalAlign = "top",
    align = "center"
  ) %>% 
  hc_legend(
    layout = "horizontal",
    verticalAlign = "top",
    align = "center",
    valueDecimals = 0
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Mint", rev = T))
  ) %>%
  highcharter::hc_add_theme(highcharter::hc_theme_smpl())



hw_grid(total_plot, prozent_plot, ncol = 2)

```

## Veränderung über Zeit

```{r}

max_rounded <- max(rki_dat$impfungen_kumulativ, na.rm = T)

# max_rounded <- nice_ceiling(max(rki_dat$impfungen_kumulativ, na.rm = T))

max_rounded <- max_rounded + max_rounded*0.05


de_map <- highcharter::download_map_data("https://code.highcharts.com/mapdata/countries/de/de-all.js")

# de_dat <- de_dat

total_plot_animated <- rki_dat %>%
  left_join(de_dat) %>% 
  mutate(day_num = as.numeric(day),
         date_label = paste0(day %>% format.Date("%d %b %Y"), "<br>", de_impfungen_kumulativ_label, " Impfungen") %>% as.factor()) %>% 
  hc_de_map_motion(
    date = "day_num",
    date_label = "date_label",
    bundesland = "bundesland",
    value = "impfungen_kumulativ",
    label = "Impfungen",
    map = de_map
  ) %>%
  hc_credits(
    enabled = TRUE, text = "Quelle: Robert Koch-Institut",
    href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
    style = list(fontSize = "12px")
  ) %>%
  hc_title(
    text = "Animation: Anzahl der Impfungen",
    verticalAlign = "top",
    align = "center"
  ) %>% 
  hc_legend(
    layout = "horizontal",
    verticalAlign = "top",
    align = "center",
    valueDecimals = 0
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Mint", rev = T)),
    min = 100, max = max_rounded
  )


max_rounded <- max(rki_dat$prozent_geimpft, na.rm = T)

# max_rounded <- nice_ceiling(max(rki_dat$prozent_geimpft, na.rm = T))

max_rounded <- max_rounded + max_rounded*0.05

prozent_plot_animated <- rki_dat %>%
  left_join(de_dat) %>% 
  mutate(day_num = as.numeric(day),
         date_label = paste0(day %>% format.Date("%d %b %Y"), "<br>", prozent_geimpft_label, " Impfungen pro 100 Einwohner") %>% as.factor()) %>% 
  hc_de_map_motion(
    date = "day_num",
    date_label = "date_label",
    bundesland = "bundesland",
    value = "prozent_geimpft",
    label = "Impfdosen pro 100 Einwohner",
    map = de_map, 
    decimal = 2
  ) %>%
  hc_credits(
    enabled = TRUE, text = "Quelle: Robert Koch-Institut",
    href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
    style = list(fontSize = "12px")
  ) %>%
  hc_title(
    text = "Animation: Impfdosen pro 100 Einwohner",
    verticalAlign = "top",
    align = "center"
  ) %>% 
  hc_legend(
    layout = "horizontal",
    verticalAlign = "top",
    align = "center",
    valueDecimals = 2
  ) %>%
  hc_colorAxis(
    stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Blues 3", rev = T)),
    min = 0, max = max_rounded
  )

total_plot_animated

# hw_grid(total_plot_animated, prozent_plot_animated, ncol = 2)

```

<br>
<br>

```{r}
prozent_plot_animated

```



<!-- ```{r, out.width="100%"} -->

<!-- prozent_plot <- hcmap( -->
<!--   "https://code.highcharts.com/mapdata/countries/de/de-all.js", -->
<!--   data = latest_dat, -->
<!--   value = "prozent_lasttime", -->
<!--   joinBy = c("name", "bundesland"), -->
<!--   name = "% der Bevölkerung geimpft", -->
<!--     dataLabels = list(enabled = TRUE, format = "{point.name}"), -->
<!--     tooltip = list( -->
<!--       valueDecimals = 2, -->
<!--       valueSuffix = "%" -->
<!--     ) -->
<!--   ) %>% -->
<!--   hc_exporting( -->
<!--     enabled = TRUE -->
<!-- )  %>%  -->
<!--   hc_credits( -->
<!--     enabled = TRUE, text = "Quelle: Robert Koch-Institut.", -->
<!--     href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html", -->
<!--     style = list(fontSize = "12px") -->
<!--   ) %>% -->
<!--   hc_title( -->
<!--     text = "Prozent der Bevölkerung geimpft" -->
<!--   ) %>%  -->
<!--   hc_legend( -->
<!--     layout = "horizontal", -->
<!--     verticalAlign = "top", -->
<!--     align = "center", -->
<!--     valueDecimals = 0 -->
<!--   )%>% -->
<!--   hc_colorAxis( -->
<!--     stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Blues 3", rev = T)) -->
<!--   ) -->

<!-- total_plot <- hcmap( -->
<!--   "https://code.highcharts.com/mapdata/countries/de/de-all.js", -->
<!--   data = latest_dat, -->
<!--   value = "impfungen_lasttime", -->
<!--   joinBy = c("name", "bundesland"), -->
<!--   name = "Anzahl der Impfungen", -->
<!--   dataLabels = list(enabled = TRUE, format = "{point.name}") -->
<!--   ) %>% -->
<!--   hc_exporting( -->
<!--     enabled = TRUE -->
<!--   )  %>%  -->
<!--   hc_credits( -->
<!--     enabled = TRUE, text = "Quelle: Robert Koch-Institut", -->
<!--     href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html", -->
<!--     style = list(fontSize = "12px") -->
<!--   ) %>% -->
<!--   hc_title( -->
<!--     text = " Anzahl der Impfungen" -->
<!--   ) %>%  -->
<!--   hc_legend( -->
<!--     layout = "horizontal", -->
<!--     verticalAlign = "top", -->
<!--     align = "center", -->
<!--     valueDecimals = 0 -->
<!--   ) %>% -->
<!--   hc_colorAxis( -->
<!--     stops = color_stops(colors = colorspace::sequential_hcl(7, palette = "Mint", rev = T)) -->
<!--   ) -->


<!-- # prozent_plot -->
<!-- #  -->
<!-- # total_plot -->

<!-- hw_grid(total_plot, prozent_plot, ncol = 2) -->

<!-- ``` -->


