---
title: "Impfdosen verabreicht über Zeit"
output: 
  html_document:
    theme: yeti
---

## {.tabset .tabset-pills}


```{r, setup, include=FALSE}
# library(vaccc19de)
library(tidyverse)
library(highcharter)


knitr::opts_chunk$set(echo = F, message = F, warning = F)

rki_dat <- readRDS("../../data/rki_dat.RDS")

source("../../R/utils.R")


latest_dat <- rki_dat %>% 
  dplyr::filter(day==max(day))


hc_mapper <- function(dat, max_size) {

  
  hc <- dat %>% 
    hchart("line", hcaes(day, prozent_geimpft),
        tooltip = list(
        name = "Impfdosen pro 100 Einwohner",
        pointFormat = "<b>{point.bundesland}</b><br><b>Impfdosen pro 100 Einwohner
:</b> {point.prozent_geimpft_label}<br><br><b>Anzahl der Impfungen:</b> {point.impfungen_kumulativ_label}")) %>%
    # Axis
    hc_yAxis(
      title = list(text = "Impfdosen pro 100 Einwohner")
    ) %>% 
    hc_xAxis(
      title = list(text = "Datum (täglich)")
      )  %>% 
    hc_exporting(
        enabled = TRUE
      )  %>% 
    hc_title(
      text = unique(dat$bundesland),
      verticalAlign = "top",
      align = "center"
    ) %>% 
    hc_credits(
      enabled = TRUE, text = "<br>Quelle: Robert Koch-Institut.",
      href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
      style = list(fontSize = "8px")
    )%>%
    hc_colors(colors =  unique(dat$colors)
    )  %>% 
    hc_yAxis(max = max_size)  %>%
    highcharter::hc_add_theme(highcharter::hc_theme_smpl())  
  return(hc)
}

max_size <- rki_dat %>% 
  pull(prozent_geimpft) %>% 
  max()

max_size <- nice_ceiling(max(max_size, na.rm = T))

# max_size 

```


### Kombiniert

Um die Anzeige einzelner Linien ein- oder auszuschalten einfach auf die entsprechende Linie in der Legende klicken.

```{r}
custom_dashes <- c("longdash", rep("Solid", 16))
custom_lines <- c(4, rep(2, 16))


combined_plot <- rki_dat %>% 
  mutate(bundesland = fct_relevel(bundesland, "Deutschland")) %>%
  mutate(color = fct_reorder(colors, as.numeric(bundesland))) 


combined_plot %>% 
    hchart("line", hcaes(day, prozent_geimpft, 
                         group = bundesland,),
           dashStyle = custom_dashes,
           lineWidth = custom_lines,
        tooltip = list(
        name = "Impfdosen pro 100 Einwohner",
        pointFormat = "<b>{point.bundesland}</b><br><b>Impfdosen pro 100 Einwohner
:</b> {point.prozent_geimpft_label}<br><br><b>Anzahl der Impfungen:</b> {point.impfungen_kumulativ_label}")) %>%
    # Axis
    hc_yAxis(
      title = list(text = "Impfdosen pro 100 Einwohner")
    ) %>% 
    hc_xAxis(
      title = list(text = "Datum (täglich)")
      )  %>% 
    hc_exporting(
        enabled = TRUE
      )  %>% 
    # hc_title(
    #   text = unique(dat$bundesland),
    #   verticalAlign = "top",
    #   align = "center"
    # ) %>% 
    hc_credits(
      enabled = TRUE, text = "<br>Quelle: Robert Koch-Institut.",
      href = "https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Impfquoten-Tab.html",
      style = list(fontSize = "8px")
    ) %>% 
    hc_colors(colors =  combined_plot$color %>% levels)  %>%
    highcharter::hc_add_theme(highcharter::hc_theme_smpl())

```

### Einzelne Panels

```{r}

rki_dat %>% 
  mutate(bundesland = fct_relevel(bundesland, "Deutschland")) %>% 
  group_split(bundesland) %>% 
  map(~hc_mapper(.x, max_size)) %>% 
  hw_grid(ncol = 3)


```

